# Site settings
title: Plaisance-McLevey Lab
email: john.mclevey@uwaterloo.ca
description: "Plaisance-McLevey Lab at the University of Waterloo"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links

people:
- name: Katie Plaisance
  pic: katie
  position: Assistant Professor
  social:
    - title: link
      url: "https://uwaterloo.ca/knowledge-integration/faculty-plaisance"
    - title: twitter
      url: https://twitter.com/katieplaisance
    - title: linkedin
      url: "https://www.linkedin.com/profile/view?id=126695447&authType=NAME_SEARCH&authToken=g7qN&locale=en_US&trk=tyah2&trkInfo=tarId%3A1412862644454%2Ctas%3Akatie%20plaisance%2Cidx%3A1-1-1"

- name: John McLevey
  pic: john
  position: Assistant Professor
  social:
    - title: twitter
      url: https://twitter.com/johnmclevey
    - title: link
      url: "http://www.johnmclevey.com" 
    - title: github
      url: http://github.com/mclevey
    # - title: linkedin
    #   url: "https://www.linkedin.com/profile/view?id=192513726&trk=nav_responsive_tab_profile_pic"
    # - title: academia.edu
    #   url: http://uwaterloo.academia.edu/JohnMcLevey

- name: Janet Michaud
  pic: janet
  position: Research Assistant
  social:
    - title: twitter
      url: https://twitter.com/
    - title: linkedin
      url: 

- name: Ben Nelson
  pic: ben
  position: Research Assistant
  social:
    - title: twitter
      url: https://twitter.com/
    - title: link
      url: "http://blsnelson.wordpress.com/" 
    - title: linkedin
      url: "https://www.linkedin.com/profile/view?id=41502798&goback=%2Enpv_41502798_*1_*1_NAME*4SEARCH_sK8x_*1_en*4US_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_tyah2_*1"

- name: Sasha Graham
  pic: sasha
  position: Research Assistant
  social:
    - title: twitter
      url: https://twitter.com/SashaVGraham
    - title: linkedin
      url: "https://www.linkedin.com/profile/view?id=158618535&authType=NAME_SEARCH&authToken=bQBl&locale=en_US&trk=tyah2&trkInfo=tarId%3A1412862783253%2Ctas%3Aalexander%20gr%2Cidx%3A2-1-4"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/johnmclevey
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/mclevey

# Postal address (add as many lines as necessary)
address:
  - line: Department of Knowledge Integration
  - line: University of Waterloo
  - line: "Waterloo, ON, Canada"

# Build settings
markdown: kramdown
permalink: pretty